const HTTP_STATUS_CODES = {
    HTTP_OK: 200,
    HTTP_BAD_REQUEST: 400,
    HTTP_UNAUTHORIZED: 401,
    HTTP_PAYMENT_REQUIRED: 402,
    HTTP_FORBIDDEN: 403,
    HTTP_NOT_FOUND: 404,
    HTTP_METHOD_NOT_ALLOWED: 405,
    HTTP_CONFLICT: 409,
    HTTP_INTERNAL_SERVER_ERROR: 500,
    HTTP_BAD_GATEWAY: 502 
}

export const QUESTION_TYPES = {
    MCQ: "MCQ",
    TF: "TF"
}

export default HTTP_STATUS_CODES